core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('pinterest/', include('pinterest.urls')),
    path('ramais/', include('ramais.urls')),
    path('adota/', include('adota.urls')),
    path('adote/divulga/', include('divulga.urls')),
    path('adote/usuario/', include('usuario.urls')),
    path('produto/', include('produto.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

ramais/urls.py
from django.urls import path
from .admin import *
from . import views

urlpatterns = [
    path('', views.lista, name='lista'),
    path('detalhe/', views.administracao, name='administracao'),
   
    # path('funcionarios/<int:id>', views.funcionarios, name='funcionarios'),
    # path('todolist/', views.todolist, name='todolist'),
    path('principal/', views.principal, name='principal'),
    path('cadastroDepartamento/', views.cadastroDepartamento, name='cadastroDepartamento'),
    path('cadastroFuncionario/', views.cadastroFuncionario, name='cadastroFuncionario'),
    path('cadastroAdministrador/', views.cadastroAdministrador, name='cadastroAdministrador'),
    path('listaDepartamento/', views.listaDepartamento, name='listaDepartamento'),
    path('listaFuncionario/', views.listaFuncionario, name='listaFuncionario'),
    path('listaAdministrador/', views.listaAdministrador, name='listaAdministrador'),
    # path('buscar/', views.buscar, name='buscar'),
    path('cadastrarDepartamento/', views.cadastrarDepartamento, name='cadastrarDepartamento'),
    path('cadastrarFuncionario/', views.cadastrarFuncionario, name='cadastrarFuncionario'),
    path('cadastrarAdministrador/', views.cadastrarAdministrador, name='cadastrarAdministrador'),
    path('excluirDepartamento/<int:id>', views.excluirDepartamento, name='excluirDepartamento'),
    path('excluirFuncionario/<int:id>', views.excluirFuncionario, name='excluirFuncionario'),
    path('excluirAdministrador/<int:id>', views.excluirAdministrador, name='excluirAdministrador'),
    path('alterarDepartamento/<int:id>', views.alterarDepartamento, name='alterarDepartamento'),
    path('alterarFuncionario/<int:id>', views.alterarFuncionario, name='alterarFuncionario'),
    path('alterarAdministrador/<int:id>', views.alterarAdministrador, name='alterarAdministrador'),
    path('login/', views.logar, name='logar'),
    path('sair/', views.sair, name='sair'),
]

home/models.py
from django.db import models

# Create your models here.

ramais/models.py
from django.db import models

# Create your models here.

class Lista_Ramais(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50)
    ramal = models.IntegerField()
    departamento = models.CharField(max_length=100)
    email = models.CharField(max_length=100, default="example@example.com")
    ip = models.CharField(max_length=100, default="192.168.254.0")

    def __str__(self):
        return self.nome


class Departamento(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Funcionario(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50)
    ramal = models.IntegerField()
    email = models.CharField(max_length=100, default="example@gmr.com.br")
    departamentoId = models.ForeignKey(Departamento, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

ramais/forms.py
from django import forms
from ramais.models import *
class DepartamentoCadastroForm(forms.Form):
    id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    nome = forms.CharField(label='Nome', max_length=50,
                           widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Digite o nome do departamento'}))

class FuncionarioCadastroForm(forms.Form):
      id = forms.IntegerField(required=False, widget=forms.HiddenInput())
      nome = forms.CharField(label='Nome', max_length=50,
                           widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Digite o nome do funcionario'}))
      ramal = forms.IntegerField(label='Ramal',
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Digite o numero do ramal'}))
      email = forms.CharField(label='Email', max_length=50,
                               widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Digite o E-mail'}))

      departamentoId = forms.ModelChoiceField(label='Departamento', queryset=Departamento.objects.all(), empty_label=None, widget=forms.Select(attrs={'class': 'form-control'}))

class AdministradorCadastroForm(forms.Form):
      id = forms.IntegerField(required=False, widget=forms.HiddenInput())
      nome = forms.CharField(label='Nome' ,max_length=50,
                           widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Digite o nome do funcionario'}))
      ramal = forms.IntegerField(label='Ramal',
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Digite o numero do ramal'}))
      email = forms.CharField(label='Email', max_length=50,
                               widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Digite o E-mail'}))

      ip = forms.CharField(label='Ip', max_length=100,
                               widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Digite o numero do ip ex:1xx.1xx.2xx.1xx'}))

      departamento = forms.CharField(label='Departamento', max_length=100,
                               widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Digite o nome do departamento.'}))

home/views.py
from django.shortcuts import render,HttpResponse
# Create your views here.

def home(request):
    """Render the home page."""
    return HttpResponse("""
    <!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Home</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gradient-to-br from-sky-100 to-indigo-200 min-h-screen flex items-center justify-center px-4">

  <div class="bg-white/80 shadow-xl rounded-xl max-w-xl w-full p-8 text-center backdrop-blur-md">
    
    <h1 class="text-3xl font-bold text-indigo-700 mb-4">Bem-vindo à Página Inicial! 👋</h1>
    
    <p class="text-gray-700 mb-2">Esta é a página inicial do seu site.</p>
    <p class="text-gray-600 mb-2">Você pode adicionar mais conteúdo aqui.</p>
    <p class="text-gray-600 mb-6">Se precisar de ajuda, entre em contato conosco.</p>
    
    <div class="flex flex-col gap-4">
      <a href="/ramais/" class="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 rounded-md transition-all duration-200">
        Lista de Ramais
      </a>
      <a href="/pinterest/login/" class="bg-pink-500 hover:bg-pink-600 text-white font-semibold py-2 rounded-md transition-all duration-200">
        Pinterest
      </a>
      <a href="/adote/usuario/logar/" class="bg-green-500 hover:bg-green-600 text-white font-semibold py-2 rounded-md transition-all duration-200">
        Adote
      </a>
    </div>

  </div>

</body>
</html>

    """)

ramais/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest
from django.db.models import F
from django.contrib.auth.models import User
# Create your views here.

def lista(request):
    if request.method == "GET":
        nome = request.GET.get('nome')
        
        departamentos = Departamento.objects.all()
        ramais = Funcionario.objects.all()
        if nome:
            departamentos = departamentos.filter(nome__icontains=nome)
           
            ramais = ramais.filter(nome__icontains=nome)
        else:
            departamentos = Departamento.objects.all()
            ramais = Funcionario.objects.all()
        return render(request, 'index.html', {'ramais': ramais, 'nome':nome, 'departamentos': departamentos})

@login_required
def administracao(request):
    if request.method == "GET":
        nome = request.GET.get('nome')
        ramal = request.GET.get('ramal')
        ip = request.GET.get('ip')
        if nome:
            ramais = Lista_Ramais.objects.filter(nome__icontains=nome)
        elif ramal:
             ramais = Lista_Ramais.objects.filter(ramal__icontains=ramal)
        # elif ip:
        #     ramais = Lista_Ramais.objects.filter(ip__icontains=ip)
        else:
           ramais = Lista_Ramais.objects.all()
        return render(request, 'administracao.html', {'ramais': ramais,'ramal':ramal,'ip':ip, 'nome':nome})    

# def funcionarios(request, id):
#     if request.method == "GET":
#         nome = request.GET.get('nome')
#         departamento = Departamento.objects.filter(id=id).first()
#         ramais = Funcionario.objects.filter(departamentoId=id)
#         return render(request, 'funcionarios.html', {'ramais': ramais, 'nome': nome, 'departamento': departamento})

# def todolist(request):
#     return render(request, 'todolist.html')

@login_required
def principal(request):
    return render(request,'principal.html')
@login_required
def cadastroDepartamento(request):

    formDepartamento = DepartamentoCadastroForm()

    return render(request, 'cadastroDepartamento.html',{'formDepartamento':formDepartamento})
@login_required
def cadastroFuncionario(request):

    formFuncionario = FuncionarioCadastroForm()

    return render(request, 'cadastroFuncionario.html',{'formFuncionario':formFuncionario})
@login_required
def cadastroAdministrador(request):

    formAdministrador = AdministradorCadastroForm()

    return render(request, 'cadastroAdministrador.html',{'formAdministrador':formAdministrador})
    pass
@login_required
def listaDepartamento(request: HttpRequest):
    if request.method == "GET":
        nome = request.GET.get('nome')
        ordenacao = request.GET.get('ordenacao')
        departamento = Departamento.objects.all()

        if nome:
            departamento = departamento.filter(nome__icontains=nome)

        # Definindo o estado padrão de ordenação
        ordenacao_estado = 'asc'

        # Definindo a ordenação padrão para o campo 'id'
        ordenacao_campo = 'id'

        # Verificando se um campo de ordenação específico foi fornecido
        if ordenacao:
            if ordenacao.startswith('-'):
                ordenacao_estado = 'desc'
                ordenacao_campo = ordenacao[1:]  # Removendo o prefixo '-' para obter o nome do campo
            else:
                ordenacao_estado = 'asc'
                ordenacao_campo = ordenacao

        # Aplicando a ordenação para o campo especificado
        if ordenacao_campo == 'id':
            departamento = departamento.order_by(F('id').asc() if ordenacao_estado == 'asc' else F('id').desc())

        else:
            departamento = departamento.order_by(F('nome').asc() if ordenacao_estado == 'asc' else F('nome').desc())

        return render(request, 'listaDepartamento.html', {'departamento': departamento, 'ordenacao_estado': ordenacao_estado})
@login_required
def listaAdministrador(request):
     if request.method == "GET":
        nome = request.GET.get('nome')
        ordenacao = request.GET.get('ordenacao')

        administrador = Lista_Ramais.objects.all()

        if nome:
            administrador = administrador.filter(nome__icontains=nome)

        # Definindo o estado padrão de ordenação
        ordenacao_estado = 'asc'

        # Definindo a ordenação padrão para o campo 'id'
        ordenacao_campo = 'id'

        # Verificando se um campo de ordenação específico foi fornecido
        if ordenacao:
            if ordenacao.startswith('-'):
                ordenacao_estado = 'desc'
                ordenacao_campo = ordenacao[1:]  # Removendo o prefixo '-' para obter o nome do campo
            else:
                ordenacao_estado = 'asc'
                ordenacao_campo = ordenacao

        # Aplicando a ordenação para o campo especificado
        if ordenacao_campo == 'id':
            administrador = administrador.order_by(F('id').asc() if ordenacao_estado == 'asc' else F('id').desc())
        elif ordenacao_campo == 'ramal':
            administrador = administrador.order_by(F('ramal').asc() if ordenacao_estado == 'asc' else F('ramal').desc())
        elif ordenacao_campo == 'email':
            administrador = administrador.order_by(F('email').asc() if ordenacao_estado == 'asc' else F('email').desc())
        elif ordenacao_campo == 'ip':
            administrador = administrador.order_by(F('ip').asc() if ordenacao_estado == 'asc' else F('ip').desc())
        elif ordenacao_campo == 'departamento':
            administrador = administrador.order_by(F('departamento').asc() if ordenacao_estado == 'asc' else F('departamento').desc())
        else:
            administrador = administrador.order_by(F('nome').asc() if ordenacao_estado == 'asc' else F('nome').desc())

        return render(request, 'listaAdministrador.html', {'administrador': administrador, 'ordenacao_estado': ordenacao_estado})

@login_required
def listaFuncionario(request):
    if request.method == "GET":
        nome = request.GET.get('nome')
        ordenacao = request.GET.get('ordenacao')

        funcionario = Funcionario.objects.all()

        if nome:
            funcionario = funcionario.filter(nome__icontains=nome)

        # Definindo o estado padrão de ordenação
        ordenacao_estado = 'asc'

        # Definindo a ordenação padrão para o campo 'id'
        ordenacao_campo = 'id'

        # Verificando se um campo de ordenação específico foi fornecido
        if ordenacao:
            if ordenacao.startswith('-'):
                ordenacao_estado = 'desc'
                ordenacao_campo = ordenacao[1:]  # Removendo o prefixo '-' para obter o nome do campo
            else:
                ordenacao_estado = 'asc'
                ordenacao_campo = ordenacao

        # Aplicando a ordenação para o campo especificado
        if ordenacao_campo == 'id':
            funcionario = funcionario.order_by(F('id').asc() if ordenacao_estado == 'asc' else F('id').desc())
        elif ordenacao_campo == 'ramal':
            funcionario = funcionario.order_by(F('ramal').asc() if ordenacao_estado == 'asc' else F('ramal').desc())
        elif ordenacao_campo == 'email':
            funcionario = funcionario.order_by(F('email').asc() if ordenacao_estado == 'asc' else F('email').desc())
        elif ordenacao_campo == 'departamentoId':
            funcionario = funcionario.order_by(F('departamentoId').asc() if ordenacao_estado == 'asc' else F('departamentoId').desc())
        else:
            funcionario = funcionario.order_by(F('nome').asc() if ordenacao_estado == 'asc' else F('nome').desc())

        return render(request, 'listaFuncionario.html', {'funcionario': funcionario, 'ordenacao_estado': ordenacao_estado})


@login_required
def cadastrarDepartamento(request):
    try:
        if request.method == 'POST':
            formDepartamento = DepartamentoCadastroForm(request.POST)
            if formDepartamento.is_valid():
                departamento = Departamento()
                departamento.nome = formDepartamento.cleaned_data['nome']
                msg = 'Departamento Cadastrado com sucesso.'
                if formDepartamento.cleaned_data['id'] is not None:
                    departamento.id = formDepartamento.cleaned_data['id']
                    msg = 'Departamento alterado com sucesso.'
                departamento.save()
                return render(request, 'cadastroDepartamento.html',{'msg':msg,'formDepartamento':DepartamentoCadastroForm()})
            else:
                raise Exception('%s, FormErrors' % formDepartamento.errors)
        else:
            raise Exception('Use POST para formularios, MethodEnvioError')
    except Exception as ex:
        msg = ex.args
        return render(request, 'cadastroDepartamento.html',{'msg':msg,'form':DepartamentoCadastroForm()})
@login_required
def cadastrarFuncionario(request):
    try:
        if request.method == 'POST':
            formFuncionario = FuncionarioCadastroForm(request.POST)
            if formFuncionario.is_valid():
                funcionario = Funcionario()
                funcionario.nome = formFuncionario.cleaned_data['nome']
                funcionario.ramal = formFuncionario.cleaned_data['ramal']
                funcionario.email = formFuncionario.cleaned_data['email']
                funcionario.departamentoId = formFuncionario.cleaned_data['departamentoId']
                msg = 'Funcionario cadastrado com sucesso.'
                if formFuncionario.cleaned_data['id'] is not None:
                    funcionario.id = formFuncionario.cleaned_data['id']
                    msg = 'Funcionario alterado com sucesso.'
                funcionario.save()
                return render(request, 'cadastroFuncionario.html', {'msg':msg,'formFuncionario':FuncionarioCadastroForm()})

ramais/templates/administracao.html
{%load static%}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{%  static 'styles.css'%}">
    <link rel="shortcut icon" href="{% static 'icon.ico' %}" type="image/x-icon">
    <script src="https://code.jquery.com/jquery-1.11.2.js"></script>
    <script type="text/javascript">
        jQuery(window).load(function ($) {
            atualizaRelogio();
            listaDeRamais();
            redesSociais();
        });

        function atualizaRelogio() {
            var momentoAtual = new Date();

            var vhora = momentoAtual.getHours();
            var vminuto = momentoAtual.getMinutes();
            var vsegundo = momentoAtual.getSeconds();

            var vdia = momentoAtual.getDate();
            var vmes = momentoAtual.getMonth() + 1;
            var vano = momentoAtual.getFullYear();

            if (vdia < 10) { vdia = "0" + vdia; }
            if (vmes < 10) { vmes = "0" + vmes; }
            if (vhora < 10) { vhora = "0" + vhora; }
            if (vminuto < 10) { vminuto = "0" + vminuto; }
            if (vsegundo < 10) { vsegundo = "0" + vsegundo; }

            var dataFormat = `${vdia}/${vmes}/${vano}`;
            var horaFormat = `${vhora}:${vminuto}:${vsegundo}`;

            document.getElementById("data").innerHTML = dataFormat;
            document.getElementById("hora").innerHTML = horaFormat;

            setTimeout("atualizaRelogio()", 1000);
        }
    </script>
    <title>Lista de Ramais e Departamentos</title>
</head>

<body>
    <nav class="navbar shadow" style="background-color: white;">
        <div class="container d-flex flex-wrap justify-content-between align-items-center">
             <a href="{% url 'lista' %}">
            <img src="{% static 'LOGO_NOVO_GMR.png' %}" alt="logo" height="70px">
             </a>
            <div class="d-flex flex-column align-items-end justify-content-center">
                <span id="data"></span>
                <span id="hora"></span>

                {% if user.is_authenticated %}
                <a class="btn btn-outline-dark btn-sm ver-mais-link mt-2" href="{% url 'principal' %}">Administração</a>
                {% else %}
                <a class="btn btn-outline-danger btn-sm ver-mais-link mt-2" href="{% url 'logar' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container my-3">
        <form action="{% url 'administracao' %}" method="get" class="d-flex flex-wrap align-items-center">
            <input type="text" name="nome" placeholder="Buscar por funcionário..." class="pesquisar">
            <input type="submit" value="Pesquisa" class="botao">
        </form>
        <form action="{% url 'administracao' %}" method="get" class="d-flex flex-wrap align-items-center ">
             <input type="number" name="ramal" placeholder="Buscar por ramal..." class="pesquisar">
         <input type="submit" value="Pesquisa" class="botao">
        </form>
           
     
    </div>

    <div class="container">
        <h4 class="text-dark">Lista de Ramais e Departamentos</h4>
        <div class="row">
            {% for lista in ramais %}
            <div class="col-sm-12 col-md-6 col-lg-4 my-2">
                <div class="card h-100">
                    <div class="card-body">
                        <a href="mailto:{{lista.email}}" class="d-flex flex-wrap align-items-baseline justify-content-between text-dark small">
                            <h6 class="card-text small">{{lista.departamento}}</h6>
                            <span class="card-title small" style="font-size: 11px;">{{lista.nome}}</span>
                            <span class="space"></span>
                            <span class="list-ramal small">{{lista.ramal}}</span>
                            {% if user.is_authenticated and user.is_superuser %}
                            <span class="card-text small">{{lista.ip}}</span>
                            {% endif %}
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('.ver-mais-link').click(function (e) {
                e.preventDefault(); 
                var url = $(this).attr('href');
                $('body').fadeOut(400, function () {
                    window.location.href = url;
                });
            });
        });
    </script>
</body>

</html>

ramais/templates/cadastroAdministrador.html
{%  extends 'base.html' %}
{% block main_content %}


<p>
    Utilize o formulário abaixo para efetuar o cadastro
    do funcionario.
</p>

<form method="POST" action="{% url 'cadastrarAdministrador' %}" style="height: 300px">

    {% csrf_token %}
    {{ formAdministrador.id }}

    <div class="form-group row">
        <label for="id_nome" class="col-sm-1">
           {{ formAdministrador.nome.label }}
        </label>

        <div class="col-sm-5">
         {{ formAdministrador.nome }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_ramal" class="col-sm-1">
            {{ formAdministrador.ramal.label }}
         </label>
        <div class="col-sm-5">
         {{ formAdministrador.ramal }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_email" class="col-sm-1">
            {{ formAdministrador.email.label }}
         </label>
     <div class="col-sm-5">
         {{ formAdministrador.email }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_email" class="col-sm-1">
            {{ formAdministrador.ip.label }}
         </label>
     <div class="col-sm-5">
         {{ formAdministrador.ip }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_departamentoId" class="col-sm-1">
            {{ formAdministrador.departamento.label }}
         </label>
     <div class="col-sm-5">
         {{ formAdministrador.departamento }}
        </div>
   </div>
   <div class="form-group row">
    <div class="col-sm-1">
    </div>
     <div class="col-sm-5">
        {% if formAdministrador.nome.value %}
        <div class="col-sm-5">
            <input type="submit" value="Atualizar" class="form-control btn btn-primary" />
        </div>
        {% else %}
        <div class="col-sm-5">
            <input type="submit" value="Cadastrar" class="form-control btn btn-primary" />
        </div>
    {% endif %}
     
   </div>
   </div>

</form>

{% if msg %} {{ msg }} {% endif %}


{% endblock %}

ramais/templates/cadastroDepartamento.html
{%  extends 'base.html' %}
{% block main_content %}
<p>
    Utilize o formulário abaixo para efetuar o cadastro
    do departamento.
</p>

<form method="POST" action="{% url 'cadastrarDepartamento' %}" style="height: 300px">

    {% csrf_token %}
    {{ formDepartamento.id }}

    <div class="form-group row">
        <label for="id_nome" class="col-sm-1">
           {{ formDepartamento.nome.label }}
        </label>

        <div class="col-sm-5">
         {{ formDepartamento.nome }}
        </div>
   </div>

    <div class="form-group row">
        <div class="col-sm-1">
        </div>
        {% if formDepartamento.nome.value %}
            <div class="col-sm-5">
                <input type="submit" value="Atualizar" class="form-control btn btn-primary" />
            </div>
        {% else %}
            <div class="col-sm-5">
                <input type="submit" value="Cadastrar" class="form-control btn btn-primary" />
            </div>
        {% endif %}
    </div>


</form>

{% if msg %} {{ msg }} {% endif %}


{% endblock %}

ramais/templates/cadastroFuncionario.html
{%  extends 'base.html' %}
{% block main_content %}


<p>
    Utilize o formulário abaixo para efetuar o cadastro
    do funcionario.
</p>

<form method="POST" action="{% url 'cadastrarFuncionario' %}" style="height: 300px">

    {% csrf_token %}
    {{ formFuncionario.id }}

    <div class="form-group row">
        <label for="id_nome" class="col-sm-1">
           {{ formFuncionario.nome.label }}
        </label>

        <div class="col-sm-5">
         {{ formFuncionario.nome }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_ramal" class="col-sm-1">
            {{ formFuncionario.ramal.label }}
         </label>
        <div class="col-sm-5">
         {{ formFuncionario.ramal }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_email" class="col-sm-1">
            {{ formFuncionario.email.label }}
         </label>
     <div class="col-sm-5">
         {{ formFuncionario.email }}
        </div>
    </div>
    <div class="form-group row">
        <label for="id_departamentoId" class="col-sm-1">
            {{ formFuncionario.departamentoId.label }}
         </label>
     <div class="col-sm-5">
         {{ formFuncionario.departamentoId }}
        </div>
   </div>
   <div class="form-group row">
    <div class="col-sm-1">
    </div>
     <div class="col-sm-5">
        {% if formFuncionario.nome.value %}
        <div class="col-sm-5">
            <input type="submit" value="Atualizar" class="form-control btn btn-primary" />
        </div>
    {% else %}
        <div class="col-sm-5">
            <input type="submit" value="Cadastrar" class="form-control btn btn-primary" />
        </div>
    {% endif %}
     
   </div>
   </div>

</form>

{% if msg %} {{ msg }} {% endif %}


{% endblock %}

ramais/templates/home.html
{%  extends 'base.html' %}



{% block main_content %}
<style>
     

        .welcome-container {
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 40px;
            text-align: center;
        }

        .welcome-message p {
            margin: 10px 0;
            color: #333;
        }

        #saudacao {
            font-size: 24px;
            font-weight: bold;
        }
</style>
<div style="height: 300px">
     <div class="welcome-container ">
          <div class="welcome-message">
               <h1>Bem Vindo,</h1>
              <h3  id="saudacao"></h3>
              
          </div>
      </div>
</div>

<script>
    var saudacaoDiv = document.getElementById('saudacao');

    function updateGreeting() {
        var user = {
            username: "{{user.username}}",
            last_login: new Date() // Supondo que last_login seja uma data
        };

        var hora = user.last_login.getHours();
        var saudacao;

        if (hora < 12) {
            saudacao = 'Bom dia';
        } else if (hora < 18) {
            saudacao = 'Boa tarde';
        } else {
            saudacao = 'Boa noite';
        }

        saudacaoDiv.textContent = saudacao + ', ' + user.username;
    }

    // Atualiza a saudação inicialmente
    updateGreeting();

    // Define um intervalo para atualizar a saudação a cada minuto
    setInterval(updateGreeting, 86400000); // Atualiza a cada 1 minuto (86400000 milissegundos)
</script>

{% endblock %}